#!/usr/bin/env python3
"""
Build a daily email digest from discovered jobs, focusing on competitive-fit roles.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path


@dataclass
class RankedJob:
    row: dict[str, str]
    competitive_score: int
    rationale: str


PENALTY_TITLE_TERMS = {
    "principal": 3,
    "staff": 2,
    "manager": 3,
    "director": 4,
    "head": 4,
    "vice president": 5,
    "vp": 5,
    "chief": 5,
    "distinguished": 4,
    "fellow": 3,
    "research scientist": 4,
}

BONUS_TITLE_TERMS = {
    "applied ai": 3,
    "ai engineer": 3,
    "ml engineer": 2,
    "machine learning engineer": 2,
    "threat intelligence": 3,
    "security engineer": 2,
    "trust": 2,
    "safety": 2,
    "intelligence": 2,
    "automation": 2,
    "platform": 1,
}


def lower(value: str) -> str:
    return (value or "").strip().lower()


def compute_competitiveness(row: dict[str, str]) -> RankedJob:
    title = lower(row.get("role_title", ""))
    snippet = lower(row.get("snippet", ""))
    fit_score = int(row.get("fit_score", "0"))
    score = fit_score * 3
    reasons: list[str] = []

    # Title-based bonuses/penalties.
    for term, bonus in BONUS_TITLE_TERMS.items():
        if term in title:
            score += bonus
            reasons.append(f"+{bonus} title match:{term}")
    for term, penalty in PENALTY_TITLE_TERMS.items():
        if term in title:
            score -= penalty
            reasons.append(f"-{penalty} seniority:{term}")

    # Prefer roles that explicitly mention production/automation/safety/intel in description.
    desc_bonus_terms = ["production", "automation", "pipeline", "security", "threat", "intel", "llm", "agent"]
    for term in desc_bonus_terms:
        if term in snippet:
            score += 1

    # Penalize heavy hard-gate academic requirements.
    if "phd required" in snippet or "doctorate required" in snippet:
        score -= 4
        reasons.append("-4 hard phd gate")

    # Remote/hybrid preference alignment.
    remote_signal = lower(row.get("remote_signal", ""))
    if remote_signal in {"remote_us", "remote_canada", "remote_us_canada"}:
        score += 2
    elif remote_signal == "hybrid":
        score += 1

    if not reasons:
        reasons.append("fit-based match")

    rationale = ", ".join(reasons[:3])
    return RankedJob(row=row, competitive_score=score, rationale=rationale)


def build_text_digest(rows: list[RankedJob], date_label: str, top_n: int) -> str:
    lines = [
        f"Daily AI Job Digest - {date_label}",
        "",
        f"Top {min(top_n, len(rows))} roles where you are likely competitive:",
        "",
    ]
    for idx, job in enumerate(rows[:top_n], start=1):
        row = job.row
        lines.extend(
            [
                f"{idx}. {row.get('role_title', '')} | {row.get('company', '')}",
                f"   Location: {row.get('location', '')} ({row.get('remote_signal', '')})",
                f"   Competitive score: {job.competitive_score} | Fit score: {row.get('fit_score', '')}",
                f"   Why: {job.rationale}",
                f"   URL: {row.get('url', '')}",
                "",
            ]
        )
    lines.extend(
        [
            "Generated by JobSearchAutomation pipeline.",
            "Next step: apply selectively to top 5-10 and use outreach drafts for first-touch messaging.",
        ]
    )
    return "\n".join(lines)


def build_html_digest(rows: list[RankedJob], date_label: str, top_n: int) -> str:
    items = []
    for idx, job in enumerate(rows[:top_n], start=1):
        row = job.row
        items.append(
            (
                f"<li><strong>{row.get('role_title', '')}</strong> | {row.get('company', '')}<br/>"
                f"Location: {row.get('location', '')} ({row.get('remote_signal', '')})<br/>"
                f"Competitive score: <strong>{job.competitive_score}</strong> | Fit score: {row.get('fit_score', '')}<br/>"
                f"Why: {job.rationale}<br/>"
                f"<a href=\"{row.get('url', '')}\">Job link</a></li>"
            )
        )
    body = "\n".join(items)
    return (
        f"<h2>Daily AI Job Digest - {date_label}</h2>"
        f"<p>Top {min(top_n, len(rows))} roles where you are likely competitive:</p>"
        f"<ol>{body}</ol>"
        "<p>Generated by JobSearchAutomation pipeline.</p>"
        "<p>Next step: apply selectively to top 5-10 and use outreach drafts for first-touch messaging.</p>"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate daily job email digest.")
    parser.add_argument("--input", required=True, help="Path to discovered_jobs.csv")
    parser.add_argument("--text-output", required=True, help="Path to plain text digest output")
    parser.add_argument("--html-output", required=True, help="Path to HTML digest output")
    parser.add_argument("--top-n", type=int, default=20, help="Number of jobs in digest")
    parser.add_argument("--min-competitive-score", type=int, default=14, help="Filter threshold")
    parser.add_argument("--date-label", default="Today", help="Date label for email")
    args = parser.parse_args()

    input_path = Path(args.input)
    text_output = Path(args.text_output)
    html_output = Path(args.html_output)
    text_output.parent.mkdir(parents=True, exist_ok=True)
    html_output.parent.mkdir(parents=True, exist_ok=True)

    with input_path.open("r", encoding="utf-8-sig", newline="") as f:
        raw_rows = list(csv.DictReader(f))

    ranked = [compute_competitiveness(r) for r in raw_rows]
    ranked = [r for r in ranked if r.competitive_score >= args.min_competitive_score]
    ranked.sort(key=lambda r: r.competitive_score, reverse=True)

    text_digest = build_text_digest(ranked, args.date_label, args.top_n)
    html_digest = build_html_digest(ranked, args.date_label, args.top_n)

    text_output.write_text(text_digest, encoding="utf-8")
    html_output.write_text(html_digest, encoding="utf-8")
    print(f"Wrote text digest: {text_output}")
    print(f"Wrote html digest: {html_output}")
    print(f"Digest jobs included: {min(args.top_n, len(ranked))}")


if __name__ == "__main__":
    main()
